http:
  routers:
    oc1-traefik:
      rule: "HostRegexp(`{[a-z]+}.oc1.nt`)"
      service: oc1-traefik

    oc2-traefik:
      rule: "HostRegexp(`{[a-z]+}.oc2.nt`)"
      service: oc2-traefik

    gcp1-traefik:
      rule: "HostRegexp(`{[a-z]+}.gcp1.nt`)"
      service: gcp1-traefik

  middlewares:

    adguardhome-themepark:
      plugin:
        rewritebody:
          lastModified: true
          rewrites:
            regex: </head>
            replacement: >
              <link rel="stylesheet"
                type="text/css"
                href="https://theme-park.dev/CSS/themes/adguard/adguard-base.css" >
              <link rel="stylesheet"
                type="text/css"
                href="https://theme-park.dev/CSS/variables/nord.css" >
              </head>

  services:
    oc1-traefik:
      loadBalancer:
        servers:
          - url: "http://100.83.6.75:90"

    oc2-traefik:
      loadBalancer:
        servers:
          - url: "http://100.102.123.68:90"

    gcp1-traefik:
      loadBalancer:
         servers:
           - url: "http://gcp1.tailnet-d10c.ts.net:90"