pilot:
    token: 

ping: {}

experimental:
  plugins:
    rewritebody:
      moduleName: "github.com/traefik/plugin-rewritebody"
      version: "v0.3.1"
 #   souin:
  #    moduleName: "github.com/darkweak/souin"
   #   version: "v1.5.10"

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"

providers:
  file:
    filename: /etc/traefik/file-provider.yml
    watch: true

  docker:
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.always-on.nt`)