api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"

providers:
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

  docker:
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\" }}.falcon.nt`)"