pilot:
  token:

ping: {}

entrypoints:
  http:
    address: ":80"

  secure:
    address: ":443"

api:
  insecure: true

metrics:
  prometheus: {}

# Dynamic config

certificatesResolvers:
  lets-encrypt:
    acme:
      email: 
      storage: /etc/traefik/acme.json
      tlsChallenge: {}

providers:
  file:
    filename: /etc/traefik/file-provider.yml
    watch: true

  docker:
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.falcon.nt`)

experimental:
  plugins:
    souin:
      moduleName: github.com/darkweak/souin
      version: v1.5.11-beta6