http:
  routers:

    home-assistant:
      rule: Host(`xx`)
      service: home-assistant@docker
      entrypoints:
        - http
        - secure
      middlewares:
        - to-https
#        - http-cache
      tls:
        certResolver: lets-encrypt
        domains:
          - xx

    aria:
      rule: "HostRegexp(`{[a-z]+}.falcon.nt`)"
      service: caddy-agneev@docker
      priority: 2

  middlewares:

    to-https:
      redirectScheme:
        scheme: https
        permanent: true

    http-cache:
      plugin:
        souin:
          api:
            souin:
              enable: true
          default_cache:
            headers:
              - Authorization
              - Content-Type
            ttl: 120s
            log_level: error
          ykeys:
            The_First_Test:
              headers:
                Content-Type: '.+'
            The_Second_Test:
              url: 'the/second/.+'
            The_Third_Test:
            The_Fourth_Test:
          surrogate_keys:
            The_First_Test:
              headers:
                Content-Type: '.+'
            The_Second_Test:
              url: 'the/second/.+'
            The_Third_Test:
            The_Fourth_Test: