version: "3.9"

volumes:
  netdata-lib:
    name: netdata-lib
  netdata-cache:
    name: netdata-cache

networks:
  default:
    name: network1
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

  dns:
    name: dns
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 8000:8080
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    ports: 
      - 9990:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#  organizr:
#    container_name: organizr
#    image: organizr/organizr
#    restart: unless-stopped
#    volumes:
#      - /opt/appdata/organizr:/config
#    environment:
#      - PGID=1001
#      - PUID=1001
#      - TZ=Asia/Kolkata
#    labels:
#      - "org.hotio.pullio.update=true"
#      - "org.hotio.pullio.notify=true"
#      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  unbound:
    container_name: unbound
    image: klutchell/unbound
    restart: unless-stopped
    ports:
      - 127.0.0.1:5053:5053/udp
    volumes:
      - type: bind
        source: /opt/appdata/unbound/unbound.conf
        target: /etc/unbound/unbound.conf
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
    networks:
      dns: {}

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    hostname: blackbox
    restart: unless-stopped
    command: 
      - "--log.level=warn"
      - "--config.file=/config/config.yml"
    cap_add:
      - CAP_NET_RAW
    ports:
      - 9115:9115
    volumes:
      - /opt/appdata/blackbox:/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  telegraf:
    image: telegraf
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    cap_add:
      - CAP_NET_RAW
    ports:
      - 10.0.0.10:9001:9000
    volumes:
      - /opt/appdata/telegraf:/etc/telegraf
    logging:
      driver: none
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1001:1001"
    command:
      - "--disable-exec"
      - "--disable-type-detection-by-header"
      - "--disable-preview-resize"
      - "--disable-thumbnails"
    environment:
      - FB_ROOT=/files
      - FB_CONFIG=/srv/config.json
      - FB_DATABASE=/srv/filebrowser.db
    volumes:
      - /opt/appdata/filebrowser:/srv
      - /opt/appdata:/files/appdata
      - /home/agneev:/files
      - /mnt:/mnt
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dig", "+short", "-p1200", "healthcheck.blocky"]
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - type: bind
        source: /opt/appdata/blocky/blocky.yml
        target: /app/config.yml
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
    networks:
      dns:
        ipv4_address: 172.19.0.254

  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    logging:
      driver: none
    volumes:
      - /opt/appdata/homer:/www/assets
    environment:
      - UID=1001
      - GID=1001
    labels:
      - traefik.http.routers.homer.rule=Host(`home.lab`)
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 81:81
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    environment:
      DB_SQLITE_FILE: "/data/npm_db.sqlite"
      DISABLE_IPV6: "true"
    volumes:
      - /opt/appdata/nginx-proxy-manager/data:/data
      - /opt/appdata/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - type: tmpfs
        target: /data/logs
        tmpfs:
          size: 32mb
      - type: tmpfs
        target: /var/cache
        tmpfs:
          size: 64mb
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: always-on
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - 19999:19999
    healthcheck:
      test: "/usr/sbin/health.sh > /dev/null 2>&1"
      interval: 60s
      timeout: 10s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /opt/appdata/netdata:/etc/netdata
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
      # System access 
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    ports:
      - 8700:80
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Asia/Kolkata
      - OOKLA_EULA_GDPR=true
    volumes:
      - /opt/appdata/speedtest-tracker:/config
      - type: tmpfs
        target: /config/log
        tmpfs:
          size: 32mb
      - type: tmpfs
        target: /config/www/node_modules
        tmpfs:
          size: 400mb
      - type: tmpfs
        target: /config/www/vendor
        tmpfs:
          size: 100mb
      - type: tmpfs
        target: /config/www/public
        tmpfs:
          size: 50mb
    labels:
      - traefik.http.routers.speedtest-tracker.rule=Host(`speedtest.always-on.nt`)
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: "/bin/netstat -pant 2> /dev/null | /bin/grep 53 > /dev/null"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/adguardhome/config:/opt/adguardhome/conf
      - /opt/appdata/adguardhome/data:/opt/adguardhome/work
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#  heimdall:
#    image: linuxserver/heimdall
#    container_name: heimdall
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
#    environment:
#      - PUID=1001
#      - PGID=1001
#      - TZ=Asia/Kolkata
#    volumes:
#      - /opt/appdata/heimdall:/config
#    labels:
#      - "org.hotio.pullio.update=true"
#      - "org.hotio.pullio.notify=true"
#      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    ports:
      - 9999:3000
    healthcheck:
      test: ["CMD", "curl", "localhost:3000", "-fso", "/dev/null"]
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:8581", "-fso", "/dev/null"]
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/homebridge:/homebridge
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer:/data
    labels:
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"