version: '3.9'

x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

x-labels: &pullio
  org.hotio.pullio.update: true
  org.hotio.pullio.notify: true
  org.hotio.pullio.discord.webhook: ${DISCORD_WEBHOOK}

volumes:
  netdata-lib:
    name: netdata-lib
  netdata-cache:
    name: netdata-cache

networks:
  default:
    name: network1
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

  dns:
    name: dns
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:

  hetrixtools:
    container_name: hetrixtools
    image: peet2k17/hetrix-agent
    restart: unless-stopped
    network_mode: host
    environment:
      HETRIX_AGENT_PARAMS: "$HETRIX_AGENT_PARAMS"
    labels:
      <<: *pullio

  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
    extra_hosts:
      - "host.docker.internal:10.0.0.10"
    ports:
      - 80:80
    environment:
      <<: *env
    volumes:
      - /opt/appdata/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.http.routers.traefik.service: api@internal
      <<: *pullio

  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    ports:
      - 9990:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      <<: *pullio

  unbound:
    container_name: unbound
    image: klutchell/unbound
    restart: unless-stopped
    ports:
      - 127.0.0.1:5053:5053/udp
    volumes:
      - /opt/appdata/unbound/unbound.conf:/etc/unbound/unbound.conf
    networks:
      dns: {}
    labels:
      traefik.enable: false
      <<: *pullio

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    hostname: blackbox
    restart: unless-stopped
    command:
     - --log.level=warn
     - --config.file=/config/config.yml
    cap_add:
     - CAP_NET_RAW
    ports:
     - 9115:9115
    volumes:
     - /opt/appdata/blackbox:/config
    labels:
     <<: *pullio

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1001:1001"
    command:
      - --disable-exec
      - --disable-type-detection-by-header
      - --disable-preview-resize
      - --disable-thumbnails
    environment:
      FB_ROOT: /files
      FB_CONFIG: /config/config.json
      FB_DATABASE: /config/filebrowser.db
    tmpfs:
      - /srv:size=1m
    volumes:
      - /opt/appdata/filebrowser:/config
      #
      - /home/agneev:/files/home
      - /opt/appdata:/files/appdata
      - /mnt:/files/mnt
    labels:
      <<: *pullio

  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dig", "+short", "-p1200", "healthcheck.blocky"]
    environment:
      <<: *env
    volumes:
      - /opt/appdata/blocky/blocky.yml:/app/config.yml
    networks:
      dns:
        ipv4_address: 172.19.0.254
    labels:
      <<: *pullio

  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    logging:
      driver: none
    environment:
      UID: 1001
      GID: 1001
    volumes:
      - /opt/appdata/homer:/www/assets
    labels:
      traefik.http.routers.homer.rule: Host(`home.lab`)
      <<: *pullio

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: always-on
    restart: unless-stopped
    healthcheck:
      test: "/usr/sbin/health.sh > /dev/null 2>&1"
    logging:
      driver: none
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - 19999:19999
    environment:
      NETDATA_CLAIM_TOKEN: $NETDATA_CLAIM_TOKEN
      NETDATA_CLAIM_URL: https://app.netdata.cloud
      NETDATA_CLAIM_ROOMS: $NETDATA_CLAIM_ROOMS
      PGID: 1001
    volumes:
      - /opt/appdata/netdata:/etc/netdata
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
      #
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      <<: *pullio

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:dev-arm
    restart: unless-stopped
    ports:
      - 8700:80
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      <<: *env
      OOKLA_EULA_GDPR: true
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtest-tracker/app:/config/www/app/Bin
      - /opt/appdata/speedtest-tracker:/config
    labels:
      traefik.http.routers.speedtest-tracker.rule: Host(`speedtest.always-on.nt`)
      <<: *pullio

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:edge
    restart: unless-stopped
    network_mode: host
    command: "-c /config/config.yml -w /config --no-check-update"
    healthcheck:
      test: "netstat -pant 2>/dev/null | grep AdGuard | grep 53 >/dev/null"
    environment:
      <<: *env
    volumes:
      - /opt/appdata/adguardhome:/config
    labels:
      traefik.http.routers.adguardhome.rule: Host(`adguard.always-on.nt`)
      traefik.http.services.adguardhome.loadbalancer.server.port: 3100
      traefik.http.routers.adguardhome.middlewares: adguardhome-themepark@file
      <<: *pullio

  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:3000", "-fso", "/dev/null"]
    ports:
      - 9999:3000
    labels:
      <<: *pullio

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:8581", "-fso", "/dev/null"]
    environment:
      <<: *env
    volumes:
      - /opt/appdata/homebridge:/homebridge
    labels:
      traefik.http.services.homebridge.loadbalancer.server.port: 8581
      <<: *pullio

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
#    healthcheck:
#      test: ["CMD", "wget", "localhost:9000", "-nv", "-t1", "--spider"]
    environment:
      TZ: Asia/Kolkata
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer:/data
    labels:
      traefik.http.services.portainer.loadbalancer.server.port: 9000 # Multiple ports exposed
      <<: *pullio

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /opt/appdata/uptime-kuma:/app/data
    environment:
      <<: *env
    labels:
      <<: *pullio