x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

x-timezone: &tz
  TZ: Asia/Kolkata

x-logging: &log
  logging:
    driver: journald

networks:

  vlan:
    name: vlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.0.0.1/24
          gateway: 10.0.0.1
          ip_range: 10.0.0.96/30 # 10.0.0.96 - 10.0.0.99

  default:
    name: network1
    ipam:
      config:
        - subnet: 172.18.0.0/16

  proxy:
    name: proxy
    ipam:
      config:
        - subnet: 172.19.1.0/24

  dns:
    name: dns
    ipam:
      config:
        - subnet: 172.19.2.0/24

services:

##### ----- DNS services ----- #####

  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.21
    restart: unless-stopped
    command: "--config /config/config.yml --work-dir /config --no-check-update"
    expose: ['80']
    environment:
      <<: *tz
    networks:
      dns:
      vlan:
        ipv4_address: 10.0.0.99
    volumes:
      - /opt/appdata/adguardhome:/config
    labels:
      traefik.enable: true
      traefik.name: dns
      traefik.docker.network: dns
      traefik.http.services.adguardhome.loadbalancer.server.port: 80
      traefik.http.routers.adguardhome.middlewares: adguardhome-themepark@file

  dnscache:
    container_name: dns-cache
    image: hezhijie0327/dnsproxy
    restart: unless-stopped
    command:
      - --upstream=https://xxxxx.cloudflare-gateway.com/dns-query
      - --bootstrap=8.8.8.8
      - --cache
      - --cache-optimistic
      - --cache-size=64000000
    networks:
      - dns

##### -------------------- #####

  iperf3:
    container_name: iperf3
    image: taoyou/iperf3-alpine
    restart: unless-stopped
    ports:
      - 5201:5201/tcp
      - 5201:5201/udp

  dashdot:
    container_name: dash.
    image: mauricenino/dashdot
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_PAGE_TITLE: dash. - always-on
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: true
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_RAM_LABEL_LIST: size,type,frequency
      DASHDOT_ACCEPT_OOKLA_EULA: true
    ports:
      - 81:3001
    volumes:
      - /:/mnt/host:ro
    labels:
      traefik.enable: true
      traefik.name: sys

  smokeping:
    container_name: smokeping
    image: linuxserver/smokeping:2.7.3-r5-ls12
    restart: unless-stopped
    hostname: ping-agneev.duckdns.org
    environment:
      <<: *env
    volumes:
      - /opt/appdata/smokeping/config:/config
      - /var/log/smokeping_data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.smokeping.rule: Host(`smokeping.nt`) || Host(`ping-agneev.duckdns.org`)

  themepark:
    container_name: theme.park
    image: gilbn/theme.park
    restart: unless-stopped
    environment:
      TP_SCHEME: http
      <<: *env
    ports:
      - 7070:80
    tmpfs:
      - /config:size=150m

  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: always
    environment:
      DOZZLE_REMOTE_HOST: tcp://falcon:2375,tcp://oracle1:2375,tcp://oc-bom1:2375,tcp://gcp1:2375
      DOZZLE_USERNAME: 
      DOZZLE_PASSWORD: 
      DOZZLE_NO_ANALYTICS: true
    ports:
      - 8000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.name: logs

  airconnect:
    container_name: airconnect
    image: 1activegeek/airconnect
    restart: unless-stopped
    network_mode: host
    environment:
      ARCH_VAR: aarch64

  vnstat:
    container_name: vnstat
    image: vergoh/vnstat
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_NAME: always-on
      HTTP_PORT: 7000
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
      <<: *tz
    volumes:
      - /opt/appdata/vnstat:/var/lib/vnstat
    labels:
      traefik.enable: true
      traefik.name: vnstat
      traefik.http.services.vnstat.loadbalancer.server.port: 7000

  vnstatrouter:
    container_name: vnstat-router
    image: vergoh/vnstat
    restart: unless-stopped
    environment:
      SERVER_NAME: orbi
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
      RUN_VNSTATD: 0
      <<: *tz
    ports:
      - 8660:8685
    volumes:
      - /mnt/res2:/var/lib/vnstat:ro
    labels:
      traefik.enable: true
      traefik.http.routers.vnstat-router.rule: Host(`vnstat.router.nt`)

  web:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    mem_limit: 200m
    command:
      - --api.insecure=true
      - --log.level=INFO
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      # Entrypoints
      - --entrypoints.http.address=:80
      # Local plugins
      - --experimental.localplugins.rewritebody.modulename=github.com/packruler/rewrite-body
      # File provider
      - --providers.file.filename=/etc/traefik/file-provider.yml
      - --providers.file.watch=true
      # Docker provider
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.defaultRule=Host(`{{ index .Labels "traefik.name" }}.nt`)
    networks:
      - default
      - proxy
      - dns
    ports:
      - 80:80
    volumes:
      - /opt/appdata/traefik/config:/etc/traefik
      - /opt/appdata/traefik/plugins:/plugins-local
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host(`web.nt`) || Host(`10.0.0.10`)
      traefik.http.routers.web.service: api@internal

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "1001:1001"
    healthcheck:
      disable: true
    environment:
      FB_DATABASE: /config/database.db
      FB_DISABLE-EXEC: true
      FB_DISABLE-TYPE-DETECTION-BY-HEADER: true
      FB_DISABLE-PREVIEW-RESIZE: true
    volumes:
      - /opt/appdata/filebrowser:/config
      #
      - /home/agneev:/srv/home
      - /opt/appdata:/srv/appdata
      - /mnt:/srv/mnt
    labels:
      traefik.enable: true
      traefik.name: files

  homer:
    container_name: homer
    image: b4bz/homer
    restart: unless-stopped
    user: "1001:1001"
    healthcheck:
      disable: true
    volumes:
      - /opt/appdata/homer:/www/assets
    labels:
      traefik.enable: true
      traefik.http.routers.homer.rule: Host(`home.lab`)

  speedtesttracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:dev-arm
    restart: unless-stopped
    ports:
      - 8700:80
    environment:
      OOKLA_EULA_GDPR: true
      <<: *env
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtest-tracker/app:/config/www/app/Bin
      - /opt/appdata/speedtest-tracker:/config
    labels:
      traefik.enable: true
      traefik.name: speedtest

  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest
    restart: unless-stopped
    ports:
      - 9999:3000

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: unless-stopped
    networks:
      - default
      - vlan
    environment:
      <<: *env
    volumes:
      - /opt/appdata/homebridge:/homebridge
    labels:
      traefik.enable: true
      traefik.name: homebridge
      traefik.docker.network: network1

  portainer:
    container_name: portainer
    image: portainer/portainer-ee:2.14.2
    restart: always
    logging:
      driver: none
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.name: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000
