version: '3.9'

x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

volumes:
  netdata-lib:
    name: netdata-lib
  netdata-cache:
    name: netdata-cache

networks:
  default:
    name: network1
    ipam:
      config:
        - subnet: 172.18.0.0/16

  dns:
    name: dns
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:

##### ----- DNS services ----- #####

  bind:
    container_name: bind
    image: ubuntu/bind9
    restart: unless-stopped
    networks:
      dns: {}
    ports:
      - 127.0.0.1:6053:53/tcp
      - 127.0.0.1:6053:53/udp
    volumes:
      - /opt/appdata/bind/conf:/etc/bind/named.conf

  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome:edge
    restart: unless-stopped
    network_mode: host
    command: "--config /config/config.yml --work-dir /tmp --no-etc-hosts --no-check-update"
    volumes:
      - /opt/appdata/adguardhome:/config
    labels:
      traefik.http.services.adguardhome.loadbalancer.server.port: 3000
      traefik.http.routers.adguardhome.middlewares: adguardhome-themepark@file

  agh2:
    container_name: adguard-home2
    image: adguard/adguardhome:edge
    restart: unless-stopped
    command: "--config /config/test.yml --work-dir /tmp --no-etc-hosts --no-check-update"
    ports:
      - 3200:3000
      - 1400:53/udp
    volumes:
      - /opt/appdata/adguardhome:/config

  alliance-dns:
    container_name: alliance-dns
    image: adguard/adguardhome:edge
    restart: unless-stopped
    command: "--config /config/config.yml --work-dir /config --no-etc-hosts --no-check-update"
    networks:
      dns:
        ipv4_address: 172.19.0.20
    ports:
      - 3100:3000
      - 127.0.0.1:1400:53/udp
    volumes:
      - /opt/appdata/adguard-alliancedns:/config
    labels:
      traefik.http.services.alliance-dns.loadbalancer.server.port: 3000

  dnsmasq:
    container_name: dnsmasq
    image: ricardbejarano/dnsmasq
    restart: unless-stopped
    command:
#      - --add-subnet=0.0.0.0/0
#      - --server=172.19.0.240
      - --server=100.102.123.68#1100
      - --cache-size=0
      - --no-resolv
      - --port=1053
      - --keep-in-foreground
    networks:
      dns: {}
    ports:
      - 1053:1053/tcp
      - 1053:1053/udp

  google-dns:
    image: spx01/blocky
    container_name: google-dns
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    networks:
      dns:
        ipv4_address: 172.19.0.10
    volumes:
      - /opt/appdata/blocky/google-dns.yml:/app/config.yml

  blocky-alliancedns:
    image: spx01/blocky
    container_name: blocky-alliancedns
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    volumes:
      - /opt/appdata/blocky/alliance-dns.yml:/app/config.yml
    networks:
      dns:
        ipv4_address: 172.19.0.243

  blocky-cf:
    image: spx01/blocky
    container_name: blocky-cf
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    ports:
      - 10.0.0.10:1053:53/udp
    volumes:
      - /opt/appdata/blocky/cloudflare.yml:/app/config.yml
    networks:
      dns:
        ipv4_address: 172.19.0.248

  unbound:
    container_name: unbound
    image: crazymax/unbound
    restart: unless-stopped
    networks:
      dns: {}
    ports:
      - 127.0.0.1:5053:5053/udp
      - 127.0.0.1:5053:5053/tcp
    tmpfs:
      - /config:size=1m
    volumes:
      - /opt/appdata/unbound/unbound-aka.conf:/etc/unbound/unbound.conf
    labels:
      traefik.enable: false

#  dnscrypt:
#    image: gists/dnscrypt-proxy
#    container_name: dnscrypt-proxy
#    restart: unless-stopped
#    network:
#      dns: {}
#    ports:
#      - 127.0.0.1:5353:5353/tcp
#      - 127.0.0.1:5353:5353/udp
#    volumes:
#      - /opt/appdata/dnscrypt-proxy/config.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml

  smartdns:
    image: agneev/smartdns
    container_name: smartdns
    restart: unless-stopped
    networks:
      dns:
        ipv4_address: 172.19.0.40
    ports:
      - 127.0.0.1:1053:53/udp
      - 127.0.0.1:1053:53/tcp
    volumes:
      - /opt/appdata/smartdns:/config

##### -------------------- #####

  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: always
    ports:
      - 8888:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  castblock:
    container_name: castblock
    image: ghcr.io/nichobi/sponsorblockcast
    restart: unless-stopped
    network_mode: host
    environment:
      SBCCATEGORIES: sponsor

  airconnect:
    container_name: airconnect
    image: 1activegeek/airconnect
    restart: unless-stopped
    network_mode: host
    environment:
      ARCH_VAR: aarch64

  vnstat:
    image: vergoh/vnstat
    container_name: vnstat
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_NAME: always-on
      HTTP_PORT: 7000
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
    volumes:
      - /opt/appdata/vnstat:/var/lib/vnstat
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      traefik.http.services.vnstat.loadbalancer.server.port: 7000

  vnstat-router:
    image: vergoh/vnstat
    container_name: vnstat-router
    restart: unless-stopped
    environment:
      SERVER_NAME: orbi
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
      RUN_VNSTATD: 0
    volumes:
      - /mnt/res:/var/lib/vnstat
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      traefik.http.routers.vnstat-router.rule: Host(`vnstat.router.nt`)
      
#  duckdns: 
#    container_name: duckdns 
#    image: linuxserver/duckdns
#    restart: unless-stopped
#    environment:
#      TZ: Asia/Kolkata

  traefik:
    container_name: traefik
    image: traefik:v2.6.0
    restart: unless-stopped
  #  healthcheck:
  #    test: ["CMD", "traefik", "healthcheck"]
    extra_hosts:
      - "host.docker.internal:10.0.0.10"
    networks:
      default: {}
      dns: {}
    ports:
      - 80:80
      - 8000:8080
    environment:
      <<: *env
    volumes:
      - /opt/appdata/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.http.routers.traefik.service: api@internal

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    restart: unless-stopped
#    hostname: blackbox
    network_mode: host
    command:
     - --log.level=warn
     - --config.file=/config/config.yml
    cap_add:
     - CAP_NET_RAW
#    ports:
#     - 9115:9115
    volumes:
     - /opt/appdata/blackbox:/config
#    labels:
#      traefik.enable: false

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1001:1001"
    environment:
      FB_ROOT: /files
      FB_CONFIG: /config/config.json
      FB_DATABASE: /config/filebrowser.db
      FB_DISABLE-EXEC: true
      FB_DISABLE-TYPE-DETECTION-BY-HEADER: true
      FB_DISABLE-PREVIEW-RESIZE: true
      FB_DISABLE-THUMBNAILS: true
    tmpfs:
      - /srv:size=1m
    volumes:
      - /opt/appdata/filebrowser:/config
      #
      - /home/agneev:/files/home
      - /opt/appdata:/files/appdata
      - /mnt:/files/mnt

  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    logging:
      driver: none
    environment:
      UID: 1001
      GID: 1001
    volumes:
      - /opt/appdata/homer:/www/assets
    labels:
      traefik.http.routers.homer.rule: Host(`home.lab`)

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: always-on
    restart: unless-stopped
    healthcheck:
      test: "/usr/sbin/health.sh > /dev/null 2>&1"
    logging:
      driver: none
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - 19999:19999
    environment:
      NETDATA_CLAIM_TOKEN: ${NETDATA_CLAIM_TOKEN}
      NETDATA_CLAIM_URL: https://app.netdata.cloud
      NETDATA_CLAIM_ROOMS: ${NETDATA_CLAIM_ROOMS}
      PGID: 1001
    volumes:
      - /opt/appdata/netdata:/etc/netdata
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
      #
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:dev-arm
    restart: unless-stopped
    ports:
      - 8700:80
    environment:
      OOKLA_EULA_GDPR: true
      <<: *env
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtest-tracker/app:/config/www/app/Bin
      - /opt/appdata/speedtest-tracker:/config

  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    ports:
      - 9999:3000

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *env
    volumes:
      - /opt/appdata/homebridge:/homebridge
    labels:
      traefik.http.services.homebridge.loadbalancer.server.port: 8581

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.services.portainer.loadbalancer.server.port: 9000 # Multiple ports exposed

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    logging:
      driver: none
    volumes:
      - /opt/appdata/uptime-kuma:/app/data
