x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata
  
x-timezone: &tz
  TZ: Asia/Kolkata

x-logging: &log
  logging:
    driver: journald

networks:
  default:
    name: network1
    ipam:
      config:
        - subnet: 172.18.0.0/16

  dns:
    name: dns
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:

##### ----- DNS services ----- #####

  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome:v0.107.8
    restart: unless-stopped
    <<: *log
    network_mode: host
    command: "--config /config/config.yml --work-dir /config --no-check-update"
    environment:
      <<: *tz
    volumes:
      - /opt/appdata/adguard-home:/config
    labels:
      traefik.enable: true
      traefik.http.routers.adguard-home.rule: Host(`dns.nt`)
      traefik.http.routers.adguard-home.middlewares: adguardhome-themepark@file
      traefik.http.services.adguard-home.loadbalancer.server.port: 3000

  dns-cache:
    container_name: dns-cache
    image: hezhijie0327/dnsproxy
    restart: unless-stopped
    command:
      - --cache
      - --cache-optimistic
      - --cache-size=64000000
      - --upstream=172.19.0.10
    networks:
      - dns
    ports:
      - 127.0.0.1:8888:53/tcp
      - 127.0.0.1:8888:53/udp

  cloudflare-dns:
    container_name: cloudflare-dns
    image: hezhijie0327/dnsproxy
    restart: unless-stopped
    command:
      - --upstream=https://xxx.cloudflare-gateway.com/dns-query
      - --bootstrap=8.8.8.8
    ports:
      - 127.0.0.1:1153:53/udp
    environment:
      <<: *tz
    networks:
      dns:
        ipv4_address: 172.19.0.10

##### -------------------- #####

  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:main
    restart: unless-stopped
    <<: *log
    volumes:
      - /opt/appdata/homepage:/app/config
    labels:
      traefik.enable: true
      traefik.name: home

  dash.:
    container_name: dash.
    image: mauricenino/dashdot
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: true
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_RAM_LABEL_LIST: size,type,frequency
      DASHDOT_ACCEPT_OOKLA_EULA: true
    ports:
      - 81:3001
    volumes:
      - /:/mnt/host:ro
    labels:
      traefik.enable: true
      traefik.name: sys

  smokeping:
    container_name: smokeping
    image: linuxserver/smokeping
    restart: unless-stopped
    <<: *log
    environment:
      <<: *env
    volumes:
      - /opt/appdata/smokeping/config:/config
      - /var/log/appdata/smokeping/data:/data
    labels:
      traefik.enable: true
      traefik.name: smokeping

  netbird:
    container_name: netbird
    image: netbirdio/netbird
    restart: unless-stopped
    network_mode: host
    privileged: true
    <<: *log
    volumes:
      - /opt/appdata/netbird:/etc/netbird

  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: always
    network_mode: none
    <<: *log
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  theme.park:
    container_name: theme.park
    image: gilbn/theme.park
    restart: unless-stopped
    <<: *log
    environment:
      TP_SCHEME: http
      <<: *env
    ports:
      - 7070:80
    tmpfs:
      - /config:size=150m

  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.name: logs

  airconnect:
    container_name: airconnect
    image: 1activegeek/airconnect
    restart: unless-stopped
    network_mode: host
    environment:
      ARCH_VAR: aarch64

  vnstat:
    container_name: vnstat
    image: vergoh/vnstat
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_NAME: always-on
      HTTP_PORT: 7000
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
      <<: *tz
    volumes:
      - /opt/appdata/vnstat:/var/lib/vnstat
    labels:
      traefik.enable: true
      traefik.name: vnstat
      traefik.http.services.vnstat.loadbalancer.server.port: 7000

  vnstat-router:
    container_name: vnstat-router
    image: vergoh/vnstat
    restart: unless-stopped
    environment:
      SERVER_NAME: orbi
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
      RUN_VNSTATD: 0
      <<: *tz
    volumes:
      - /mnt/res:/var/lib/vnstat:ro
    labels:
      traefik.enable: true
      traefik.http.routers.vnstat-router.rule: Host(`vnstat.router.nt`)

  traefik:
    container_name: traefik
    image: traefik:v2.8
    restart: unless-stopped
    <<: *log
    command:
      - --api.insecure=true
      - --log.level=INFO
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      # Entrypoints
      - --entrypoints.http.address=:80
      # Local plugins
      - --experimental.localplugins.rewritebody.modulename=github.com/packruler/rewrite-body
      # File provider
      - --providers.file.filename=/etc/traefik/file-provider.yml
      - --providers.file.watch=true
      # Docker provider
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.defaultRule=Host(`{{ index .Labels "traefik.name" }}.always-on.nt`)
    extra_hosts:
      - "host.docker.internal:10.0.0.10"
    mem_limit: 200m
    networks:
      - default
      - dns
    ports:
      - 80:80
    volumes:
      - /opt/appdata/traefik/config:/etc/traefik
      - /opt/appdata/traefik/plugins:/plugins-local
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.name: traefik
      traefik.http.routers.traefik.service: api@internal

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: "1001:1001"
    environment:
      FB_DATABASE: /config/database.db
      FB_DISABLE-EXEC: true
      FB_DISABLE-TYPE-DETECTION-BY-HEADER: true
      FB_DISABLE-PREVIEW-RESIZE: true
    volumes:
      - /opt/appdata/filebrowser:/config
      #
      - /home/agneev:/srv/home
      - /opt/appdata:/srv/appdata
      - /mnt:/srv/mnt
    labels:
      traefik.enable: true
      traefik.name: filebrowser

  homer:
    container_name: homer
    image: b4bz/homer
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - /opt/appdata/homer:/www/assets
    labels:
      traefik.enable: true
      traefik.http.routers.homer.rule: Host(`home.lab`)

  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:dev-arm
    restart: unless-stopped
    <<: *log
    ports:
      - 8700:80
    environment:
      OOKLA_EULA_GDPR: true
      <<: *env
    tmpfs:
      - /config/www:size=500m
      - /config/log:size=32m
    volumes:
      - /opt/appdata/speedtest-tracker/app:/config/www/app/Bin
      - /opt/appdata/speedtest-tracker:/config
    labels:
      traefik.enable: true
      traefik.name: speedtest

  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest
    restart: unless-stopped
    <<: *log
    ports:
      - 9999:3000

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    <<: *log
    environment:
      <<: *env
    volumes:
      - /opt/appdata/homebridge:/homebridge
    labels:
      traefik.enable: true
      traefik.name: homebridge
      traefik.http.services.homebridge.loadbalancer.server.port: 8581

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    <<: *log
    ports:
      - 9000:9000
    volumes:
      - /opt/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.name: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000