x-timezone: &tz
  TZ: Asia/Kolkata

x-environment-vars: &env
  PUID: 1001
  PGID: 1001
  UMASK: 002
  <<: *tz

x-logging: &log
  logging:
    driver: journald

networks:
  default:
    name: network1
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:

  dash.:
    container_name: dash.
    image: mauricenino/dashdot
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: true
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_RAM_LABEL_LIST: size,type,frequency
    ports:
      - 81:3001
    volumes:
      - /:/mnt/host:ro
    labels:
      traefik.enable: true
      traefik.name: sys

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr
    restart: unless-stopped
    user: "1001:1001"
    expose:
      - 7474
    environment:
      <<: *env
    volumes:
      - /opt/appdata/autobrr:/config
    labels:
      traefik.enable: true
      traefik.name: autobrr

  paperless-ngx:
    image: linuxserver/paperless-ngx
    container_name: paperless-ngx
    restart: unless-stopped
    <<: *log
    volumes:
      - /opt/appdata/paperless-ngx/config:/config
      - /opt/appdata/paperless-ngx/data:/data
    environment:
      <<: *env
    labels:
      traefik.enable: true
      traefik.name: docs

  youtube-dl-material:
    container_name: youtube-dl-material
    image: tzahi12345/youtubedl-material
    restart: unless-stopped
    <<: *log
    environment:
      UID: 1001
      GID: 1001
    volumes:
      - /opt/appdata/youtube-dl-material/appdata:/app/appdata
      - /opt/appdata/youtube-dl-material/subscriptions:/app/subscriptions
      #
      - /opt/storage/youtube-dl:/app/video
      - /opt/storage/youtube-dl:/app/audio
    labels:
      traefik.enable: true
      traefik.name: youtube-dl

  webnet-tools:
    container_name: webnet-tools
    image: agneev/webnet-tools
    restart: unless-stopped
    <<: *log
    labels:
      traefik.enable: true
      traefik.name: network-tools

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr
    restart: unless-stopped
    <<: *log
    volumes:
      - /opt/appdata/homarr/configs:/app/data/configs
      - /opt/appdata/homarr/icons:/app/public/icons
    labels:
      traefik.enable: true
      traefik.name: homarr

  netbird:
    container_name: netbird
    image: netbirdio/netbird
    restart: unless-stopped
    network_mode: host
    privileged: true
    <<: *log
    volumes:
      - /opt/appdata/netbird:/etc/netbird

  samba:
    container_name: samba
    image: elswork/samba
    restart: unless-stopped
    command: "-u xxx"
    environment:
      <<: *tz
    ports:
      - 445:445
    volumes:
      - /opt/appdata/samba:/etc/samba
      #
      - /mnt:/mnt
      - ~/:/ssd
      - /opt/storage:/nas

  plextraktsync:
    container_name: plextraktsync
    image: ghcr.io/taxel/plextraktsync
    restart: unless-stopped
    user: "1001:1001"
    command: watch
    <<: *log
    depends_on:
      - plex
    environment:
      PTS_LOG_DIR: /logs
      <<: *tz
    tmpfs:
      - /logs:size=10m,uid=1001,gid=1001
    volumes:
      - /opt/appdata/plextraktsync:/app/config

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    <<: *log
    command: tunnel run --token ${CLOUDFLARED_TOKEN}

  aria2:
    container_name: aria2
    image: hurlenko/aria2-ariang
    restart: unless-stopped
    <<: *log
    command:
      - --dir=/aria2/data
      - --max-connection-per-server=4
      - --max-concurrent-downloads=5
      - --file-allocation=falloc
      - --enable-mmap=true
      - --disk-cache=64M
      - --continue=true
      # Misc
      - --on-download-complete=/aria2/conf/aria-post-dl.sh
      - --save-session=/aria2/conf/aria2.session
      - --input-file=/aria2/conf/aria2.session
      - --enable-rpc=true
      - --rpc-listen-all=true
      - --rpc-allow-origin-all=true
    environment:
      ARIA2RPCPORT: 80
      <<: *env
    volumes:
      - /opt/appdata/aria2:/aria2/conf
      - ~/downloads:/aria2/data
    labels:
      traefik.enable: true
      traefik.name: aria2

  duplicacy:
    container_name: duplicacy
    image: hotio/duplicacy
    restart: unless-stopped
    hostname: duplicacy
    <<: *log
    environment:
      <<: *env
    tmpfs:
      - /cache:size=200m
    volumes:
      - /opt/appdata/duplicacy:/config
      - /opt/appdata/duplicacy/logs:/logs
      - /opt/appdata/duplicacy/license.sh:/etc/cont-init.d/02-license
      #
      - /opt/appdata:/appdata
      - ~/:/ssd
    labels:
      traefik.enable: true
      traefik.name: duplicacy

  vnstat:
    image: vergoh/vnstat
    container_name: vnstat
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_NAME: falcon
      HTTP_PORT: 7000
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
      <<: *tz
    volumes:
      - /opt/appdata/vnstat/vnstat.conf:/etc/vnstat.conf
      - /opt/appdata/vnstat:/var/lib/vnstat
    labels:
      traefik.enable: true
      traefik.name: vnstat
      traefik.http.services.vnstat.loadbalancer.server.port: 7000

  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: always
    network_mode: none
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    container_name: traefik
    image: traefik:v2.8
    restart: unless-stopped
    <<: *log
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      # Entrypoints
      - --entrypoints.http.address=:80
#      - --entrypoints.secure.address=:443
      # SSL
#      - --certificatesResolvers.cloudflare.acme.email=${ACME_EMAIL}
#      - --certificatesResolvers.cloudflare.acme.storage=/etc/traefik/cloudflare.json
#      - --certificatesResolvers.cloudflare.acme.dnsChallenge.provider=manual
#      - --certificatesResolvers.duckdns.acme.email=${ACME_EMAIL}
#      - --certificatesResolvers.duckdns.acme.storage=/etc/traefik/duckdns.json
#      - --certificatesResolvers.duckdns.acme.dnsChallenge.provider=duckdns
      # File provider
      - --providers.file.filename=/etc/traefik/file-provider.yml
      - --providers.file.watch=true
      # Docker
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.defaultRule=HostRegexp(`{{ index .Labels "traefik.name" }}.{i:falcon.nt|agneev.ml}`)
    extra_hosts:
      - "host.docker.internal:10.0.0.11"
    environment:
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
    ports:
      - 80:80
#      - 443:443
    volumes:
      - /opt/appdata/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.name: traefik
      traefik.http.routers.traefik.service: api@internal

  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.name: logs

  archivebox:
    container_name: archivebox
    image: archivebox/archivebox
    restart: unless-stopped
    <<: *log
    environment:
      MEDIA_MAX_SIZE: 750m
      <<: *env
    volumes:
      - /opt/appdata/archivebox:/data
    labels:
      traefik.enable: true
      traefik.name: archivebox

  librespot:
    container_name: librespot
    image: agneev/librespot-java
    restart: unless-stopped
    <<: *log
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /opt/appdata/librespot-java:/config

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1001:1001"
    environment:
      FB_DATABASE: /config/database.db
      FB_DISABLE-EXEC: true
      FB_DISABLE-TYPE-DETECTION-BY-HEADER: true
      FB_DISABLE-PREVIEW-RESIZE: true
    volumes:
      - /opt/appdata/filebrowser:/config
      #
      - ~/:/srv/home
      - /opt/storage:/srv/storage
      - /opt/appdata:/srv/appdata
      - /mnt:/srv/mnt
    labels:
      traefik.enable: true
      traefik.name: files

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    <<: *log
    user: "1001:1001"
    depends_on:
      - prometheus
    volumes:
      - /opt/appdata/grafana/config:/etc/grafana
      - /opt/appdata/grafana/data:/var/lib/grafana
    labels:
      traefik.enable: true
      traefik.name: grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    user: "1001:1001"
    <<: *log
    command:
#      - --storage.local.target-heap-size=
      - --log.level=warn
      - --config.file=/config.yml
    environment:
      <<: *tz
    volumes:
      - /opt/appdata/prometheus/prometheus.yml:/config.yml
      - /opt/appdata/prometheus:/prometheus
    labels:
      traefik.enable: true
      traefik.name: prom

  shairport-sync:
    container_name: shairport-sync
    image: mikebrady/shairport-sync
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/appdata/shairport-sync/config.conf:/etc/shairport-sync.conf
    devices:
      - /dev/snd:/dev/snd

  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    restart: unless-stopped
    <<: *log
    environment:
      <<: *env
    volumes:
      - /opt/appdata/freshrss:/config
    labels:
      traefik.enable: true
      traefik.name: freshrss

  yacht:
    container_name: yacht
    image: selfhostedpro/yacht:devel
    restart: always
    <<: *log
    environment:
      DISABLE_AUTH: True
      SECRET_KEY: key
      <<: *env
    volumes:
      - /opt/appdata/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.name: yacht

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny
    restart: unless-stopped
    <<: *log
    cap_add:
      - SYS_RAWIO
    volumes:
      - /opt/appdata/scrutiny/config:/opt/scrutiny/config
      - /opt/appdata/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    devices:
      - /dev/sda:/dev/sda:ro
      - /dev/sdb:/dev/sdb:ro
     # - /dev/sdc:/dev/sdc:ro
     # - /dev/sdd:/dev/sdd:ro
     # - /dev/sde:/dev/sde:ro
     # - /dev/sdf:/dev/sdf:ro
    labels:
      traefik.enable: true
      traefik.name: scrutiny

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    <<: *log
    environment:
      <<: *tz
    volumes:
      - /opt/appdata/home-assistant:/config
    labels:
      traefik.enable: true
      traefik.name: home-assistant
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123

  node-red:
    container_name: node-red
    image: nodered/node-red
    restart: unless-stopped
    user: "1001:1001"
    <<: *log
    environment:
      <<: *env
    volumes:
      - /opt/appdata/node-red:/data
    labels:
      traefik.enable: true
      traefik.name: node-red

  qbittorrent:
    container_name: qbittorrent
    image: hotio/qflood #:release-4.3.9--4.7.0
    restart: unless-stopped
    <<: *log
    environment:
      <<: *env
    volumes:
      - /opt/appdata/qbittorrent:/config
      - ~/scripts/qbt_post_dl.sh:/script.sh:ro
      #
      - ~/downloads:/downloads
      - ~/drive-local/local/qbt:/drive/local/qbt
      - /mnt/knox:/knox
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.service: qbittorrent
      traefik.http.routers.qbittorrent.rule: Host(`qbt.falcon.nt`)
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      # Flood
      traefik.http.routers.flood.service: flood
      traefik.http.routers.flood.rule: Host(`flood.falcon.nt`)
      traefik.http.services.flood.loadbalancer.server.port: 3000

  plex:
    container_name: plex
    image: hotio/plex
    restart: unless-stopped
    network_mode: host
    environment:
      <<: *env
    tmpfs:
      - /transcode:size=4g
    volumes:
      - /opt/appdata/plex:/config
      - /var/log/plex/logs:/config/Logs
      #
      - /mnt/mfs-drive:/drive
      - /mnt/knox:/knox
    labels:
      traefik.enable: true
      traefik.name: plex
      traefik.http.services.plex.loadbalancer.server.port: 32400

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    <<: *log
    ports:
      - 8181:8181
    environment:
      TP_THEME: plex
      TP_SCHEME: http
      TP_DOMAIN: 10.0.0.10:7070
      DOCKER_MODS: ghcr.io/gilbn/theme.park:tautulli
      <<: *env
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/appdata/plex/Logs:/plex-logs:ro
    labels:
      traefik.enable: true
      traefik.name: tautulli

  autoscan:
    container_name: autoscan
    image: hotio/autoscan
    restart: unless-stopped
    <<: *log
    ports:
      - 100.125.93.18:3030:3030
    environment:
      <<: *env
    volumes:
      - /opt/appdata/autoscan:/config

  radarr:
    container_name: radarr
    image: linuxserver/radarr:nightly
    restart: unless-stopped
    <<: *log
    depends_on:
      - autoscan
    ports:
      - 7878:7878
    environment:
      TP_THEME: onedark
      TP_COMMUNITY_THEME: true
      TP_SCHEME: http
      TP_DOMAIN: 10.0.0.10:7070
      DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
      <<: *env
    volumes:
      - /opt/appdata/radarr:/config
      - ~/scripts/radarr_connect.sh:/script.sh
      #
      - /mnt/mfs-drive:/drive
      - /mnt/knox:/knox
    labels:
      traefik.enable: true
      traefik.name: radarr

  radarr4k:
    container_name: radarr4k
    image: linuxserver/radarr:nightly
    restart: unless-stopped
    <<: *log
    depends_on:
     - autoscan
    ports:
     - 7879:7878
    environment:
     TP_THEME: organizr
     TP_ADDON: radarr-4k-logo
     TP_SCHEME: http
     TP_DOMAIN: 10.0.0.10:7070
     DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
     <<: *env
    volumes:
     - /opt/appdata/radarr4k:/config
     - ~/scripts/radarr_connect.sh:/script.sh
     #
     - /mnt/mfs-drive:/drive
     - /mnt/knox:/knox
    labels:
      traefik.enable: true
      traefik.name: radarr4k

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    <<: *log
    depends_on:
      - autoscan
    ports:
      - 8989:8989
    environment:
      TP_THEME: plex
      TP_SCHEME: http
      TP_DOMAIN: 10.0.0.10:7070
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
      <<: *env
    volumes:
      - /opt/appdata/sonarr:/config
      - ~/scripts/sonarr_connect.sh:/script.sh
      #
      - /mnt/mfs-drive:/drive
      - /mnt/knox:/knox
    labels:
      traefik.enable: true
      traefik.name: sonarr

  sonarr4k:
    container_name: sonarr4k
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    <<: *log
    depends_on:
      - autoscan
    ports:
      - 8990:8989
    environment:
      TP_THEME: organizr
      TP_ADDON: sonarr-4k-logo
      TP_SCHEME: http
      TP_DOMAIN: 10.0.0.10:7070
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
      <<: *env
    volumes:
      - /opt/appdata/sonarr4k:/config
      - ~/scripts/sonarr_connect.sh:/script.sh
      #
#      - /mnt/mfs-drive:/drive
#      - /mnt/knox:/knox
    labels:
      traefik.enable: true
      traefik.name: sonarr4k

  unpackerr:
    container_name: unpackerr
    image: hotio/unpackerr
    restart: unless-stopped
    <<: *log
    depends_on:
      - radarr
      - sonarr
#    - radarr4k
#    - sonarr4k
    environment:
      UN_FOLDER_0_PATH: /drive/local/qbt
      UN_FOLDER_0_DELETE_AFTER: 0
      #
      UN_SONARR_0_URL: http://sonarr:8989
      UN_SONARR_0_API_KEY: ${SONARR_API_KEY}
      UN_RADARR_0_URL: http://radarr:7878
      UN_RADARR_0_API_KEY: ${RADARR_API_KEY}
      # Sonarr4K
#      UN_SONARR_1_URL: http://sonarr4k:8989
#      UN_SONARR_1_API_KEY: ${SONARR4K_API_KEY}
      # Radarr4K
#      UN_RADARR_1_URL: http://radarr4k:7878
#      UN_RADARR_1_API_KEY: ${RADARR4K_API_KEY}
      <<: *env
    tmpfs:
      - /config:size=1m
    volumes:
      - ~/drive-local/local/qbt:/drive/local/qbt