version: '3.8'

x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

services:

  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
    volumes:
      - /opt/appdata/vaultwarden:/data
#    labels:
#      traefik.http.routers.vaultwarden.tls: true

  jackett:
    container_name: jackett
    image: hotio/jackett
    restart: unless-stopped
    ports:
      - 100.83.6.75:9117:9117
    environment:
      <<: *env
    volumes:
      - /opt/appdata/jackett:/config

  qbit-manage:
    container_name: qbit-manage
    image: hotio/qbitmanage
    environment:
#      ARGS
      <<: *env
    volumes:
      - /opt/appdata/qbit-manage:/config

  plextraktsync:
    container_name: plextraktsync
    image: ghcr.io/taxel/plextraktsync
    restart: unless-stopped
    user: "1001:1001"
    command: watch
    environment:
      PTS_LOG_DIR: /logs
      TZ: Asia/Kolkata
    tmpfs:
      - /logs:size=10m,uid=1001,gid=1001
    volumes:
      - /opt/appdata/plextraktsync:/app/config

  bazarr4k:
    container_name: bazarr4k
    image: linuxserver/bazarr
    restart: unless-stopped
    extra_hosts:
      - "radarr4k.falcon.nt:100.120.109.59"
      - "sonarr4k.falcon.nt:100.120.109.59"
    environment:
      DOCKER_MODS: ghcr.io/gilbn/theme.park:bazarr
      TP_THEME: aquamarine
      <<: *env
    volumes:
      - /opt/appdata/bazarr4k:/config
      - /mnt/mfs-drive:/drive

  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    ports:
      - 90:90
      - 443:443
      - 8000:8080
    volumes:
      - /opt/appdata/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

#  dozzle:
#    container_name: dozzle
#    image: amir20/dozzle
#    restart: unless-stopped
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro

  unpackerr:
    container_name: unpackerr
    image: hotio/unpackerr
    restart: unless-stopped
    extra_hosts:
      - "radarr.falcon.nt:100.120.109.59"
      - "radarr4k.falcon.nt:100.120.109.59"
      - "sonarr.falcon.nt:100.120.109.59"
      - "sonarr4k.falcon.nt:100.120.109.59"
    environment:
      # Sonarr
      UN_SONARR_0_URL: http://sonarr.falcon.nt
      UN_SONARR_0_API_KEY: 
      # Sonarr4K
      UN_SONARR_1_URL: http://sonarr4k.falcon.nt
      UN_SONARR_1_API_KEY: 
      # Radarr
      UN_RADARR_0_URL: http://radarr.falcon.nt
      UN_RADARR_0_API_KEY: 
      # Radarr4k
      UN_RADARR_1_URL: http://radarr4k.falcon.nt
      UN_RADARR_1_API_KEY: 
    tmpfs:
      - /config:size=1m
    volumes:
      - /home/ubuntu/drive-local/local/qbt:/drive/local/qbt

  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: "/bin/netstat -pant 2> /dev/null | /bin/grep 53 > /dev/null"
    volumes:
      - /opt/appdata/adguardhome/workdir:/opt/adguardhome/work
      - /opt/appdata/adguardhome/config:/opt/adguardhome/conf

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:nightly
    restart: unless-stopped
    ports:
      - 100.83.6.75:9696:9696
    environment:
      TP_THEME: dracula
      DOCKER_MODS: ghcr.io/gilbn/theme.park:prowlarr
      <<: *env
    volumes:
      - /opt/appdata/prowlarr:/config

  overseerr:
    container_name: overseerr
    image: hotio/overseerr:nightly
    restart: unless-stopped
    extra_hosts:
      - "radarr.falcon.nt:100.120.109.59"
      - "radarr4k.falcon.nt:100.120.109.59"
      - "sonarr.falcon.nt:100.120.109.59"
      - "sonarr4k.falcon.nt:100.120.109.59"
      - "tautulli.falcon.nt:100.120.109.59"
    environment:
      <<: *env
    volumes:
      - /opt/appdata/overseerr:/config

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    extra_hosts:
      - "radarr.falcon.nt:100.120.109.59"
      - "sonarr.falcon.nt:100.120.109.59"
    environment:
      DOCKER_MODS: ghcr.io/gilbn/theme.park:bazarr
      TP_THEME: organizr
      <<: *env
    volumes:
      - /opt/appdata/bazarr:/config
      - /mnt/mfs-drive:/drive

  qbittorrent:
    container_name: qbittorrent
    image: hotio/qflood:release-4.3.9--4.7.0
    restart: unless-stopped
    ports:
      - 100.83.6.75:8100:8080
      - 100.83.6.75:8101:3000
      - 32044:32044/tcp
      - 32044:32044/udp
    environment:
      <<: *env
    volumes:
      - /opt/appdata/qbittorrent:/config
      #
      - /home/ubuntu/drive-local/local/qbt:/drive/local/qbt
      - /home/ubuntu/scripts/qbt.sh:/script.sh:ro