version: '3.8'

x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

x-labels: &pullio
  org.hotio.pullio.update: "true"
  org.hotio.pullio.notify: "true"
  org.hotio.pullio.discord.webhook: ${DISCORD_WEBHOOK}

services:

  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  plextraktsync:
    container_name: plextraktsync
    image: ghcr.io/taxel/plextraktsync
    restart: unless-stopped
    user: "1001:1001"
    command: watch
    environment:
      PTS_LOG_DIR: /logs
      TZ: Asia/Kolkata
    tmpfs:
      - /logs:size=10m,uid=1001,gid=1001
    volumes:
      - /opt/appdata/plextraktsync:/app/config
    labels:
      <<: *pullio

  bazarr4k:
    container_name: bazarr4k
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      DOCKER_MODS: ghcr.io/gilbn/theme.park:bazarr
      TP_THEME: aquamarine
      <<: *env
    volumes:
      - /opt/appdata/bazarr4k:/config
      - /mnt/mfs-drive:/drive
    labels:
      <<: *pullio

  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --entrypoints.http.address=:90
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.oc1.nt`)
    ports:
      - 90:90
      - 8000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      <<: *pullio

  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      <<: *pullio

  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - 1200:53/udp
    environment:
      TZ: Asia/Kolkata
    volumes:
      - /opt/appdata/blocky/blocky.yml:/app/config.yml:ro
    labels:
      <<: *pullio

  unpackerr:
    container_name: unpackerr
    image: hotio/unpackerr
    restart: unless-stopped
    environment:
      # Sonarr
      UN_SONARR_0_URL:
      UN_SONARR_0_API_KEY:
      # Sonarr4K
      UN_SONARR_1_URL:
      UN_SONARR_1_API_KEY:
      # Radarr
      UN_RADARR_0_URL:
      UN_RADARR_0_API_KEY:
      # Radarr4K
      UN_RADARR_1_URL:
      UN_RADARR_1_API_KEY:
      <<: *env
    tmpfs:
      - /config:size=1m
    volumes:
      - /home/ubuntu/drive-local/local/qbt:/drive/local/qbt
    labels:
      <<: *pullio

  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    ports:
      - 9999:3000
    labels:
      <<: *pullio

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:edge
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: "/bin/netstat -pant 2> /dev/null | /bin/grep 53 > /dev/null"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/adguardhome/workdir:/opt/adguardhome/work
      - /opt/appdata/adguardhome/config:/opt/adguardhome/conf
    labels:
      <<: *pullio

  prowlarr:
    container_name: prowlarr
    image: hotio/prowlarr:nightly
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      <<: *env
    volumes:
      - /opt/appdata/prowlarr:/config
    labels:
      <<: *pullio

  socks5-proxy:
    image: serjs/go-socks5-proxy
    container_name: socks5-proxy
    restart: unless-stopped
    ports:
      - 32069:1080
    environment:
      - TZ=Asia/Kolkata
      - PROXY_USER=agneev
    labels:
      <<: *pullio

  overseerr:
    container_name: overseerr
    image: hotio/overseerr
    restart: unless-stopped
    environment:
      <<: *env
    volumes:
      - /opt/appdata/overseerr:/config
    labels:
      <<: *pullio

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      DOCKER_MODS: ghcr.io/gilbn/theme.park:bazarr
      TP_THEME: organizr
      <<: *env
    volumes:
      - /opt/appdata/bazarr:/config
      - /mnt/mfs-drive:/drive
    labels:
      <<: *pullio

  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      DB_SQLITE_FILE: /data/npm_db.sqlite
      DISABLE_IPV6: "true"
    volumes:
      - /opt/appdata/nginx-proxy-manager/data:/data
      - /opt/appdata/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    labels:
      <<: *pullio

  qbittorrent:
    container_name: qbittorrent
    image: hotio/qflood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:8080", "-fso", "/dev/null"]
    ports:
      - 8100:8080
      - 8101:3000
    environment:
      <<: *env
    volumes:
      - /opt/appdata/qbittorrent:/config
      #
      - /home/ubuntu/drive-local/local/qbt:/drive/local/qbt
      - /home/ubuntu/scripts/qbt.sh:/script.sh:ro
    labels:
      <<: *pullio