x-env: &env
  PGID: 1001
  PUID: 1001
  UMASK: 002
  TZ: Asia/Kolkata

services:

  overseerr:
    container_name: overseerr
    image: linuxserver/overseerr
    restart: unless-stopped
    environment:
      <<: *env
    volumes:
      - ./overseerr:/config

  iperf3:
    container_name: iperf3
    image: taoyou/iperf3-alpine
    restart: unless-stopped
    ports:
      - 5201:5201/tcp
      - 5201:5201/udp

  vnstat:
    image: vergoh/vnstat
    container_name: vnstat
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_NAME: oracle1
      HTTP_PORT: 7000
      LARGE_FONTS: 1
      HTTP_LOG: /dev/null
      TZ: Asia/Kolkata
    volumes:
      - /opt/appdata/vnstat/vnstat.conf:/etc/vnstat.conf
      - /opt/appdata/vnstat:/var/lib/vnstat
    labels:
      traefik.http.services.vnstat.loadbalancer.server.port: 7000

  traefik-home:
    container_name: traefik-home
    image: traefik
    restart: unless-stopped
    command:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.oc1.nt`)
    extra_hosts:
      - "host.docker.internal:10.0.0.15"
    ports:
      - 90:80
      - 8090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  unpackerr:
    container_name: unpackerr
    image: golift/unpackerr
    restart: unless-stopped
    environment:
      # Sonarr
      UN_SONARR_0_URL: http://falcon.tailnet-d10c.ts.net:8989
      UN_SONARR_0_API_KEY: ${SONARR_API_KEY}
      # Sonarr4K
      UN_SONARR_1_URL: http://falcon.tailnet-d10c.ts.net:8990
      UN_SONARR_1_API_KEY: ${SONARR4K_API_KEY}
      # Radarr
      UN_RADARR_0_URL: http://falcon.tailnet-d10c.ts.net:7878
      UN_RADARR_0_API_KEY: ${RADARR_API_KEY}
      # Radarr4K
      UN_RADARR_1_URL: http://falcon.tailnet-d10c.ts.net:7879
      UN_RADARR_1_API_KEY: ${RADARR4K_API_KEY}
      <<: *env
    volumes:
      - ~/drive-local/local/qbt:/media/local/qbt

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    ports:
      - 8100:8080
      - 32044:32044/tcp
      - 32044:32044/udp
    environment:
      <<: *env
    volumes:
      - /opt/appdata/qbittorrent:/config
      #
      - ~/drive-local/local/qbt:/media/local/qbt
      - ~/scripts/qbt.sh:/script.sh:ro
    labels:
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
