version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-file: "5"
    max-size: "10m"

volumes:
  netdata_lib:
  netdata_cache:

services:

  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - /opt/appdata/homer:/www/assets
    environment:
      - UID=1001
      - GID=1001
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  nginxproxymanager:
    container_name: nginxproxymanager
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 10.0.0.10:80:80
      - 10.0.0.10:9000-9010:9000-9010
    environment:
      DB_SQLITE_FILE: "/data/npm_db.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - /opt/appdata/nginx-proxy-manager/data:/data
      - /opt/appdata/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: always-on
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - 10.0.0.10:19999:19999
    healthcheck:
      test: ["CMD", "/usr/sbin/health.sh", ">/dev/null", "2>&1"]
      interval: 60s
      timeout: 10s
      retries: 3
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      # Configuration
      - /opt/appdata/netdata:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      # System access 
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#  yacht:
#    container_name: yacht
#    image: selfhostedpro/yacht:devel
#    logging: *default-logging
#    restart: unless-stopped
#    environment:
#      - PUID=1001
#      - PGID=1001
#      - SECRET_KEY=key
#      - DISABLE_AUTH=True
#    volumes:
#      - /opt/appdata/yacht:/config
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/localtime:/etc/localtime:ro
#    labels:
#      - "org.hotio.pullio.update=true"
#      - "org.hotio.pullio.notify=true"
#      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  speedtest-tracker:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest-arm
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 10.0.0.10:8700:80
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Asia/Kolkata
      - OOKLA_EULA_GDPR=true
    volumes:
      - /opt/appdata/speedtest-tracker:/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    logging: *default-logging
    network_mode: host
    healthcheck:
      test: "/bin/netstat -pant 2> /dev/null | /bin/grep 53 > /dev/null"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/adguardhome/workdir:/opt/adguardhome/work
      - /opt/appdata/adguardhome/config:/opt/adguardhome/conf
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/heimdall:/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  qbittorrent:
    container_name: qbittorrent
    image: hotio/qflood
    logging: *default-logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:8080", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Asia/Kolkata
      - FLOOD_AUTH=false
    volumes:
      - /opt/appdata/qbittorrent:/config
      # Download folders
      - /home/agneev/qbt:/downloads
      - /mnt:/mnt
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#   statping:
#     container_name: statping
#     image: statping/statping:dev
#     restart: unless-stopped
#     logging:
#       driver: none
#     volumes:
#       - /opt/appdata/statping:/app
#    healthcheck:
#      test: ["CMD", "curl", "localhost:8080", "-fso", "/dev/null"]
#    labels:
#      - "org.hotio.pullio.update=true"
#      - "org.hotio.pullio.notify=true"
#      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 10.0.0.10:8200:3000
    healthcheck:
      test: ["CMD", "curl", "localhost:3000", "-fso", "/dev/null"]
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    logging: *default-logging
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:8581", "-fso", "/dev/null"]
    environment:
      - TZ=Asia/Kolkata
      - PGID=1001
      - PUID=1001
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /opt/appdata/homebridge:/homebridge
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer_data:/data
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
