version: "3.9"

volumes:
  netdata-lib:
    name: netdata-lib
  netdata-cache:
    name: netdata-cache

networks:
  default:
    name: skynet
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:

#   photoprism:
#     container_name: photoprism
#     image: photoprism/photoprism
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "localhost:2342", "-so", "/dev/null"]
#     security_opt:
#       - seccomp:unconfined
#       - apparmor:unconfined
#     working_dir: "/photoprism"
#     volumes:
#       - /opt/appdata/photoprism:/photoprism/storage
#       - /mnt/knox/photos:/photoprism/originals
#     environment:
#       PHOTOPRISM_UID: 1001
#       PHOTOPRISM_GID: 1001
#       PHOTOPRISM_READONLY: "false"
#       PHOTOPRISM_PUBLIC: "true"
#       PHOTOPRISM_EXPERIMENTAL: "false"
#       PHOTOPRISM_HTTP_HOST: "0.0.0.0"
#       PHOTOPRISM_HTTP_PORT: 2342
#       PHOTOPRISM_HTTP_COMPRESSION: "none"     # Improves transfer speed and bandwidth utilization (none or gzip)
#       PHOTOPRISM_DATABASE_DRIVER: "sqlite"
#       PHOTOPRISM_DARKTABLE_PRESETS: "false"   # Enables Darktable presets and disables concurrent RAW conversion
#       PHOTOPRISM_THUMB_FILTER: "lanczos"      # Resample filter, best to worst: blackman, lanczos, cubic, linear
#       PHOTOPRISM_THUMB_UNCACHED: "true"       # Enables on-demand thumbnail rendering (high memory and cpu usage)
#       PHOTOPRISM_THUMB_SIZE: 2048             # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
#       # PHOTOPRISM_THUMB_SIZE: 4096           # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
#       PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680    # On-demand rendering size limit (default 7680, min 720, max 7680)
#       PHOTOPRISM_JPEG_SIZE: 7680              # Size limit for converted image files in pixels (720-30000)
#       PHOTOPRISM_JPEG_QUALITY: 92             # Set to 95 for high-quality thumbnails (25-100)
#       TF_CPP_MIN_LOG_LEVEL: 0                 # Show TensorFlow log messages for development
#     labels:
#       - "org.hotio.pullio.update=true"
#       - "org.hotio.pullio.notify=true"
#       - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  archivebox:
    container_name: archivebox
    image: archivebox/archivebox:master
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:8000/admin/login", "-so", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - MEDIA_MAX_SIZE=750m
    volumes:
      - /opt/appdata/archivebox:/data
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  autoscan:
    container_name: autoscan
    image: hotio/autoscan
    restart: unless-stopped
    ports:
      - 100.120.109.59:3030:3030
    healthcheck:
      test: ["CMD", "curl", "localhost:3030", "-so", "/dev/null"]
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/autoscan:/config
      - /mnt/mfs-drive:/drive
      - /mnt/knox:/knox:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  plextraktsync:
    container_name: plextraktsync
    image: ghcr.io/taxel/plextraktsync
    restart: unless-stopped
    user: "1001:1001"
    command: "watch"
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "10.0.0.11:32400/identity"]
    logging: 
      driver: none
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/plextraktsync:/app/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#  spotifyd:
#    container_name: spotifyd
#    image: zewelor/spotifyd
#    restart: unless-stopped
#    volumes:
#      - type: bind
#        source: /opt/appdata/spotifyd/spotifyd.conf
#        target: /etc/spotifyd.conf
#      - type: tmpfs
#        target: /cache
#        tmpfs:
#          size: 64mb
#    devices:
#      - /dev/snd:/dev/snd

  hdidle:
    container_name: hdidle
    image: hotio/hdidle
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - ARGS=-i 600
    volumes:
      - type: tmpfs
        target: /config
        tmpfs:
          size: 1mb
    devices:
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "1001:1001"
    command:
      - "--disable-exec"
      - "--disable-type-detection-by-header"
      - "--disable-preview-resize"
      - "--disable-thumbnails"
    environment:
      - FB_ROOT=/files
      - FB_CONFIG=/srv/config.json
      - FB_DATABASE=/srv/filebrowser.db
    volumes:
      - /opt/appdata/filebrowser:/srv
      - /opt/appdata:/files/appdata
      - /home/agneev:/files
      - /mnt:/mnt
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#   chronograf:
#     image: chronograf
#     container_name: chronograf
#     restart: unless-stopped
#     user: "1001:1001"
#     environment: 
#       - LOG_LEVEL=error
#       - REPORTING_DISABLED
#     volumes:
#       - /opt/appdata/chronograf:/var/lib/chronograf
#     labels:
#       - "org.hotio.pullio.update=true"
#       - "org.hotio.pullio.notify=true"
#       - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#   influxdb:
#     image: influxdb
#     container_name: influxdb
#     restart: unless-stopped
#     user: "1001:1001"
#     volumes:
#       - /opt/appdata/influxdb/data:/var/lib/influxdb2
#       - /opt/appdata/influxdb/config:/etc/influxdb2
#     labels:
#       - "org.hotio.pullio.update=true"
#       - "org.hotio.pullio.notify=true"
#       - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "1001"
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "localhost:3000"]
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.server
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - /opt/appdata/grafana/config:/etc/grafana
      - /opt/appdata/grafana/data:/var/lib/grafana
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    user: "1001:1001"
    command: 
      - "--log.level=warn"
      - "--config.file=/etc/prometheus/prometheus.yml"
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "localhost:9090"]
    volumes:
      - /opt/appdata/prometheus/config:/etc/prometheus
      - /opt/appdata/prometheus/data:/prometheus
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  shairport-sync:
    container_name: shairport-sync
    image: mikebrady/shairport-sync
    restart: unless-stopped
    network_mode: host
    command: "-c /config/shairport-sync.conf"
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /opt/appdata/shairport-sync:/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/freshrss:/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: falcon
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - 19999:19999
    healthcheck:
      test: "/usr/sbin/health.sh > /dev/null 2>&1"
      interval: 60s
      timeout: 10s
    volumes:
      - /opt/appdata/netdata:/etc/netdata
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
      # System access 
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht:devel
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "localhost:8000"]
    environment:
      - PUID=1001
      - PGID=1001
      - SECRET_KEY=key
      - DISABLE_AUTH=True
    volumes:
      - /opt/appdata/yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
  
  scrutiny:
    container_name: scrutiny
    image: hotio/scrutiny
    restart: unless-stopped
    logging: 
      driver: none
    cap_add:
      - SYS_RAWIO
    healthcheck:
      test: ["CMD", "curl", "localhost:8080", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - INTERVAL=10800
    volumes:
      - /run/udev:/run/udev:ro
      - /opt/appdata/scrutiny:/config
    devices:
      - /dev/sda:/dev/sda:ro
      - /dev/sdb:/dev/sdb:ro
      - /dev/sdc:/dev/sdc:ro
      - /dev/sdd:/dev/sdd:ro
      - /dev/sde:/dev/sde:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
      
#  node-red:
#    container_name: node-red
#    image: nodered/node-red
#    restart: unless-stopped
#    user: "1001:1001"
#    environment:
#      - TZ=Asia/Kolkata
#    volumes:
#      - /opt/appdata/nodered:/data
#    labels:
#      - "org.hotio.pullio.update=true"
#      - "org.hotio.pullio.notify=true"
#      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

#   code-server:
#     container_name: code-server
#     image: linuxserver/code-server
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "localhost:8443", "-fso", "/dev/null"]
#     environment:
#       - PUID=1001
#       - PGID=1001
#       - TZ=Asia/Kolkata
#     volumes:
#       - /opt/appdata/code-server:/config
#       # Project folders
#       - /home/agneev:/config/workspace/home
#     labels:
#       - "org.hotio.pullio.update=true"
#       - "org.hotio.pullio.notify=true"
#       - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    ports:
      - 80:80
    environment:
      DB_SQLITE_FILE: "/data/npm_db.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - /opt/appdata/nginx-proxy-manager/data:/data
      - /opt/appdata/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:8123", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /opt/appdata/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      # MariaDB database
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  qbittorrent:
    container_name: qbittorrent
    image: hotio/qflood
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:8080", "-fso", "/dev/null"]
    environment:
      - FLOOD_AUTH=true
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/qbittorrent:/config
      # Download directories
      - /home/agneev/drive-local/local/qbt:/drive/local/qbt
      - /mnt/knox:/knox
      # Post download script
      - type: bind
        source: /home/agneev/scripts/qbt_post_dl.sh
        target: /scripts/qbt_post_dl.sh
        read_only: true
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  plex:
    image: hotio/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "localhost:32400/identity", "-fso", "/dev/null"]
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    depends_on:
      - tautulli
    volumes:
      - /opt/appdata/plex:/config
      - type: tmpfs
        target: /transcode
        tmpfs:
          size: 3gb
      - /mnt/mfs-drive:/drive:ro
      - /mnt/knox:/knox:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  tautulli:
    container_name: tautulli
    image: hotio/tautulli
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:8181", "-fso", "/dev/null"]
    environment:
      - TP_HOTIO=true
      - TP_THEME=plex
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/theme-park/tautulli:/etc/cont-init.d/99-themepark
      - /opt/appdata/plex/Logs:/plex-logs:ro
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  radarr:
    container_name: radarr
    image: hotio/radarr:nightly
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:7878", "-fso", "/dev/null"]
    ports:
      - 100.120.109.59:7878:7878
    environment:
      - TP_HOTIO=true
      - TP_THEME=onedark
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/radarr:/config
      - /opt/theme-park/radarr:/etc/cont-init.d/99-themepark
      - /mnt/mfs-drive:/drive
      - /mnt/knox:/knox
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  radarr4k:
    container_name: radarr4k
    image: hotio/radarr:nightly
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:7879", "-fso", "/dev/null"]
    ports:
      - 100.120.109.59:7879:7879
    environment:
      - TP_HOTIO=true
      - TP_THEME=organizr-dark
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/radarr4k:/config
      - /opt/theme-park/radarr:/etc/cont-init.d/99-themepark
      - /mnt/mfs-drive:/drive
      - /mnt/knox:/knox
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"

  sonarr:
    container_name: sonarr
    image: hotio/sonarr:nightly
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:8989", "-fso", "/dev/null"]
    ports:
      - 100.120.109.59:8989:8989
    environment:
      - TP_HOTIO=true
      - TP_THEME=plex
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/sonarr:/config
      - /opt/theme-park/sonarr:/etc/cont-init.d/99-themepark
      - /mnt/mfs-drive:/drive
      - /mnt/knox:/knox
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"